### PR TITLE
NIFIREG-75 Fix User Groups for Composite Provider Config

### PR DESCRIPTION
**Pull request by kevdoran**
Removes user existence check from FileUserGroupProvider when group is created or updated. Replaces it with check in the Authorizer Decorator class created by Authorizer Factory, so that all providers are used. Also fixes bug when searching for group membership by user that returns results across all providers.

Also updates a package name in the authorizers.xml template.

UI fix for group membership deletion icon in user side panel.

### CODE REVIEW

**Comment by kevdoran** [comment]
Upon further discussion, may go with a different approach here. please hold off on merging this for now

**Comment by kevdoran** [comment]
This has been updated with the latest approach

**Comment by bbende** [comment]
Reviewing...

**Comment by bbende** [comment]
+1 Ran through a full test with NiFi & Registry both configured with a composite user-group-provider, and put an LDAP user into a file-based group, and then made a bucket and gave the group access to that bucket, verified the LDAP user could use that bucket from NiFi... nice work

**Pull request closed without merging**
