### PR TITLE
NIFIREG-172 Adds Swagger UI

### PR DESCRIPTION
**Pull request by kevdoran**
Contains the following changes:

- Adds self-hosted Swagger UI to nifi-registry-web-api WAR at /swagger/ui.html
- Updates NOTICE for included ALv2 licensed source
- Adds Jersey filter exclusion for resources starting with /swagger/*
- Adds top-level authorizable resource type for /swagger/*
- Updates ResourceAuthorizationFilter configuration to include swagger resource type
- Corrects name of Position model object in Swagger specification
- Corrects duplicate operationId/nickname field for methods in FlowResource and BucketFlowResource

For reviewers:

- Verify /nifi-registry-api/swagger/ui.html is accessible and working in unsecured mode.
- Verify /nifi-registry-api/swagger/swagger.json returns a good Swagger spec.
- In secured mode, an initial admin should have access, as should any user who is granted read access to the "/swagger" resource
- Verify changes to NOTICE in source code and nifi-registry-assembly

### CODE REVIEW

**Comment by bbende** [comment]
Swagger part looks good, nice work!

I think nifi-registry-assembly/NOTICE  just needs the 2017 changed to 2018 at the top.

**Comment by kevdoran** [comment]
Good eye, will update. And thanks for the review!

**Comment by kevdoran** [comment]
@bbende I updated the copyright date range and also made a couple other updates to the README files while I was there. Let me know if you are good with these changes. Thanks!

**Comment by bbende** [comment]
Thanks! looks good, will merge

**Pull request closed without merging**
