### PR TITLE
NIFIREG-408 Adding clients for tenants and policies

### PR DESCRIPTION
**Pull request by bbende**
NOTE: This is includes the PR for NIFIREG-409 as that was required to make the integration test work correctly in this PR.

Thank you for submitting a contribution to Apache NiFi Registry.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFIREG-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFIREG-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi-registry` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-registry-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-registry-assembly`?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by kevdoran** [comment]
Thanks @bbende. I started reviewing this. Locally I rebased on `main` after merging #291. 

I'm not sure why, but although the integration tests are passing in GH Actions, they are failing for me locally

```
Results :


Tests in error:
  SecureNiFiRegistryClientIT.testTenantsClient:290 » SSL Connection has been shu...
```

Looking into it, but wanted to make you aware and ask if you had seen this?

**Comment by bbende** [comment]
Thanks for reviewing!  Hmmm I do remember seeing this error once, but I think I only encountered it when running the IT test from Intellij and then after fixing the other revision problem I never saw it again, but interesting that it is happening from a maven build here.

**Comment by bbende** [comment]
I can't figure out why that error seems to happen only on the updateUserGroup call, but I tried a few things and so far switching the order in the test where it does "create, retrieve, update, delete", instead of "create, update, retrieve, delete", seems to make it consistently pass. 

I feel like this is more some testing environmental issue, since even in the previous scenario, the create and update were working on the server side, but for some reason the connection was closed by the time the client tried to read the response.

**Comment by kevdoran** [comment]
Hey, @bbende. I agree that it is a testing issue, and also that this change, although it doe not fix the root cause, does make the test seemingly pass reliably. +1 from me, will merge. We can monitor the testing setup to see if we need to fi the root cause at some point... thanks!

**Pull request closed without merging**
