### PR TITLE
NIFIREG-266 Add Selenium UI automated tests for bucket use cases

### PR DESCRIPTION
**Pull request by andrewmlim**
Requirements for tests to run:

-an unsecured Registry instance running on the default port of 18080
-Chrome browser

Tests run explicitly with the following build command referencing the test profile:

mvn install -Pselenium_tests

Also added a data-automation-id to the Identity/Bucket Name field when configuring a bucket.

### CODE REVIEW

**Comment by bbende** [comment]
Looks like there are some check-style violations, you can run with -Pcontrib-check locally to verify them:
```
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITRenameBucket.java[6] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - org.openqa.selenium.*.
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITRenameBucket.java[119] (sizes) LineLength: Line is longer than 200 characters (found 225).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITRenameBucket.java[123] (sizes) LineLength: Line is longer than 200 characters (found 204).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITDeleteSingleBucketCancel.java[6] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - org.openqa.selenium.*.
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITDeleteSingleBucketCancel.java[100] (sizes) LineLength: Line is longer than 200 characters (found 225).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITDeleteSingleBucketCancel.java[104] (sizes) LineLength: Line is longer than 200 characters (found 204).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITCreateMultipleBuckets.java[6] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - org.openqa.selenium.*.
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITCreateMultipleBuckets.java[111] (sizes) LineLength: Line is longer than 200 characters (found 225).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITCreateMultipleBuckets.java[115] (sizes) LineLength: Line is longer than 200 characters (found 204).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITCreateDuplicateBucket.java[6] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - org.openqa.selenium.*.
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITCreateDuplicateBucket.java[125] (sizes) LineLength: Line is longer than 200 characters (found 225).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITCreateDuplicateBucket.java[129] (sizes) LineLength: Line is longer than 200 characters (found 204).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITRenameBucketDuplicate.java[6] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - org.openqa.selenium.*.
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITRenameBucketDuplicate.java[137] (sizes) LineLength: Line is longer than 200 characters (found 223).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITRenameBucketDuplicate.java[163] (sizes) LineLength: Line is longer than 200 characters (found 225).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITRenameBucketDuplicate.java[167] (sizes) LineLength: Line is longer than 200 characters (found 204).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITCreateBucket.java[6] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - org.openqa.selenium.*.
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITCreateBucket.java[79] (sizes) LineLength: Line is longer than 200 characters (found 225).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITCreateBucket.java[83] (sizes) LineLength: Line is longer than 200 characters (found 204).
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITCreateBucketCancel.java[6] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - org.openqa.selenium.*.
[WARNING] src/test/java/org/apache/nifi/registry/ui/ITDeleteSingleBucket.java[6] (imports) AvoidStarImport: Using the '.*' form of import should be avoided - org.openqa.selenium.*.
```

**Comment by andrewmlim** [comment]
Thanks @bbende !  Will take a look.

**Comment by andrewmlim** [comment]
@bbende Corrected the check-style violations and added Apache license header to the tests.

**Comment by andrewmlim** [comment]
Closing this PR, as both commits are in https://github.com/apache/nifi-registry/pull/185

**Pull request closed without merging**
