### PR TITLE
NIFIREG-289 - UI - isolate webpack loaders used specifically for code…

### PR DESCRIPTION
**Pull request by rfellows**
… coverage purposes

### CODE REVIEW

**Comment by RynoRn** [comment]
I assume this will fix [NIFI-6377](https://issues.apache.org/jira/browse/NIFI-6377).

**Comment by rfellows** [comment]
> I assume this will fix [NIFI-6377](https://issues.apache.org/jira/browse/NIFI-6377).

Yes, I believe it will.

**Comment by mcgilman** [comment]
@rfellows can you please rebase this.

**Comment by rfellows** [comment]
@mcgilman, I rebased it.

**Comment by scottyaslan** [comment]
Reviewing...

**Pull request closed without merging**
